services:
  service:
    build:
      context: .
      dockerfile: docker/dev.Dockerfile
      args:
        SERVICE_NAME: service_name
    volumes:
      - ./logs:/var/log/service/
    depends_on:
      service-db:
        condition: service_healthy
    ports:
      - '12021:80'

  service-db:
    build:
      context: .
      dockerfile: docker/db/dev.Dockerfile
    ports:
    - "10001:3306"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 2s
    env_file:
      - ./docker/db/db.env
    volumes:
      - ./docker/db/migration/:/docker-entrypoint-initdb.d
      - service_db:/var/lib/mysql

volumes:
  service_db:
